openapi: 3.0.0
info:
  title: API Lua
  description: Opensource API to generate astrological charts using Kerykeion.
  version: 1.0.0
servers:
  - url: http://localhost:5050
paths:
  /mapas/natal:
    post:
      summary: Generate a natal chart
      description: Creates a natal chart based on the provided personal data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Name of the person.
                ano:
                  type: integer
                  description: Year of birth.
                mes:
                  type: integer
                  description: Month of birth.
                dia:
                  type: integer
                  description: Day of birth.
                hora:
                  type: integer
                  description: Hour of birth.
                minuto:
                  type: integer
                  description: Minute of birth.
                local:
                  type: string
                  description: Place of birth.
                pais:
                  type: string
                  description: Country of birth.
              required:
                - nome
                - ano
                - mes
                - dia
                - hora
                - minuto
                - local
                - pais
      responses:
        "200":
          description: Natal chart successfully generated.
          content:
            application/xml:
              schema:
                type: string
                description: SVG representation of the natal chart.
        "400":
          description: Invalid input data.
