openapi: 3.0.0
info:
  title: API Lua
  description: Opensource API to generate astrological charts using Kerykeion.
  version: 1.0.0
servers:
  - url: http://localhost:5050
paths:
  /chart/{chartType}:
    post:
      summary: Generate an astrological chart
      description: Creates an astrological chart based on the provided personal data and chart type.
      parameters:
        - name: chartType
          in: path
          required: true
          schema:
            type: string
            enum: [Natal]
          description: Type of the astrological chart to generate. Currently, only 'Natal' is supported.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the person.
                birthdate:
                  type: string
                  description: Birthdate in the format 'YYYY-MM-DD HH:MM'.
                location:
                  type: string
                  description: Place of birth.
                countryCode:
                  type: string
                  description: Country code of birth.
              required:
                - name
                - birthdate
                - location
                - countryCode
      responses:
        "200":
          description: Astrological chart successfully generated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  chart:
                    type: string
                    format: content
                description: Json object with chart attribute that represents SVG of the astrological chart.
        "400":
          description: Invalid input data.
        "404":
          description: Unsupported chart type.
